package com.tgl.sample;

import com.tgl.sample.Message;

rule "Hello World"

    when
        m : Message( status == Message.HELLO, $myMessage : message)
    then
        System.out.println($myMessage);
        m.setMessage("Goodbye cruel world");
        m.setStatus(Message.GOODBYE);
        update(m);
end

rule "Goodbye"

    when
        Message ( status == Message.GOODBYE, printMessage : message)
    then
        System.out.println(printMessage);
end


